### ISSUE TITLE
small fix to exif.js path

### ISSUE THREAD

**Issue by fernicar** [shiimizu/ComfyUI_smZNodes#103]
https://github.com/shiimizu/ComfyUI_smZNodes/blob/ff96c4e813a4ca4a0f4f62fd5b3349a39ddc0e07/web/metadata.js#L38
there is no "js" folder, to be replaced with:
exifPath = '/extensions/ComfyUI_smZNodes/exif.js'

**Comment by shiimizu** [comment]
Thanks for the heads up!
