### ISSUE TITLE
Where do I find the SDXL CLIP Text Encode++ nodes?

### ISSUE THREAD

**Issue by FugueSegue** [shiimizu/ComfyUI_smZNodes#106]
I found the regular CLIP Text Encode++ nodes. But on the main page of the repo there an image of these nodes:

<img width="799" alt="266273584-ec85fd20-2b83-43cd-9f19-5aba34034e2a CROP" src="https://github.com/user-attachments/assets/45e67f4e-4b51-4737-b130-f03bd1cd493f">

Where do I find them? I'm sorry but it's not obvious to me.

**Comment by shiimizu** [comment]
See `https://github.com/shiimizu/ComfyUI_smZNodes/issues/58#issuecomment-1960277897`

**Comment by FugueSegue** [comment]
Thank you. I see the Tip written beneath the table of options on the code page.

I recommend that you clearly state that the SDXL widget options are available at the very beginning of the section title, "Clip Text Encode++". In between this section title and the example images of the node, you should clearly state that there is one node and one node only. At first glance, it looks like there are four separate types of nodes. But I assume that it is the same node configured four different ways. If that is the case, please clearly state this.

Other than that, your node seems to work very well. I am incorporating it into some of my basic workflows. Replicating the alternating words trick from Automatic1111 was something that I always thought ComfyUI lacked.

Thanks again.

**Comment by FugueSegue** [comment]
Thank you. I see the Tip written beneath the table of options on the code page.

I recommend that you clearly state that the SDXL widget options are available at the very beginning of the section title, "Clip Text Encode++". In between this section title and the example images of the node, you should clearly state that there is one node and one node only. At first glance, it looks like there are four separate types of nodes. But I assume that it is the same node configured four different ways. If that is the case, please clearly state this.

Other than that, your node seems to work very well. I am incorporating it into some of my basic workflows. Replicating the alternating words trick from Automatic1111 was something that I always thought ComfyUI lacked.

Thanks again.
