### ISSUE TITLE
Why are my nodes showing up with a ton of missing widgets?

### ISSUE THREAD

**Issue by Hezow** [shiimizu/ComfyUI_smZNodes#109]
![Capture](https://github.com/user-attachments/assets/95b11ef6-247c-421a-b8bd-6259dac9f965)

**Comment by Hezow** [comment]
@shiimizu Thanks

**Comment by twe00074** [comment]
@shiimizu 
This is an awesome addon, but an example workflow might be helpful. I thought these nodes weren't working because of a different version of Comfy. Yes, I didn't try to connect the model first because I can't remember any node working that way.
