### ISSUE TITLE
Prompt editing (and alternating words) not working on comfy and comfy++ parser

### ISSUE THREAD

**Issue by EgorkaSanyok** [shiimizu/ComfyUI_smZNodes#112]
Adding prompt editing syntax into a prompt seems to not do anything, unless the parser is A1111, full, compel, or fixed attention . I'm not sure if this is intended, but it would be nice to have them for comfy and comfy++ as well.

**Comment by shiimizu** [comment]
Yes, it’s intended. As an alternative, there’s [comfyui-prompt-control](https://github.com/asagi4/comfyui-prompt-control).
