### ISSUE TITLE
Not the same as A1111.

### ISSUE THREAD

**Issue by za-wa-n-go** [shiimizu/ComfyUI_smZNodes#17]
I have tried with WebUI 1.6.0 and A1111parser and it does not seem to give the same results.

ComfyUI
![ComfyUI_00029_](https://github.com/shiimizu/ComfyUI_smZNodes/assets/118154415/46489d7e-4915-406b-afaf-2d1f53d2c52d)

WebUI
![00003-156680208700286](https://github.com/shiimizu/ComfyUI_smZNodes/assets/118154415/a3778e2f-8ae1-4301-8133-0cbebaba8d98)

**Comment by za-wa-n-go** [comment]
<img width="1084" alt="image" src="https://github.com/shiimizu/ComfyUI_smZNodes/assets/118154415/a9c8a186-a0d3-4cf4-aea2-d8fa731e78d2">

<img width="1336" alt="image" src="https://github.com/shiimizu/ComfyUI_smZNodes/assets/118154415/2ca534ad-8cb0-44da-b0d0-c8d045cbf99d">

**Comment by za-wa-n-go** [comment]
Soryyyy.
I didn't check my explanation enough.

**Comment by za-wa-n-go** [comment]
Not the same, but something close was found.

Comfy
![ComfyUI_00031_](https://github.com/shiimizu/ComfyUI_smZNodes/assets/118154415/573dee18-8406-466a-97bb-9176e376dd45)

A1111
![00004-156680208700286](https://github.com/shiimizu/ComfyUI_smZNodes/assets/118154415/263329e4-4b4d-4674-bc53-0d6afb8d2094)

Please let me know if there are more settings that can be brought together.

**Comment by shiimizu** [comment]
SDXL models default to `-2` clip skip in A1111 and ComfyUI. Also, `DPM2 Karras` != `DPM++ 2M Karras`. In ComfyUI, `DPM2` is `dpm_2`.

Here's an example using `DPM++ 2M Karras`:

<div align="center">

|stable-diffusion-webui|A1111 parser|
|:---:|:---:|
|  ![04393-156680208700286-beautiful scenery nature glass bottle landscape, , purple galaxy bottle,](https://github.com/shiimizu/ComfyUI_smZNodes/assets/54494639/ae9befaf-103a-492e-83a2-d970dddd128f) |  ![ComfyUI_temp_pyoxy_00004_](https://github.com/shiimizu/ComfyUI_smZNodes/assets/54494639/bda0a9cf-4396-4241-9239-d15d90e2507b)  |



Workflows are in the images.
</div>

There also seems to be a bug in ComfyUI. I had to revert the following commits to get those results:
- https://github.com/comfyanonymous/ComfyUI/commit/c9e4a8c9e5a5baabd86fdb192ef79d3b288408a6
- https://github.com/comfyanonymous/ComfyUI/commit/fb4bf7f591e4c0917e66814370216ef7858c6b6a

**Comment by za-wa-n-go** [comment]
Thank you!
Is the comfy side aware of this bug?

**Comment by shiimizu** [comment]
> Thank you!

You're welcome :)

> Is the comfy side aware of this bug?

No, someone should report the bug.

**Comment by Robson1970** [comment]
Found this
https://github.com/comfyanonymous/ComfyUI/discussions/118

"Noise on ComfyUI is generated on the CPU while the a1111 UI generates it on the GPU. This makes ComfyUI seeds reproducible across different hardware configurations but makes them different from the ones used by the a1111 UI."

**Comment by za-wa-n-go** [comment]
thankyou!
Now a1111 should also be able to select cpu.
