### ISSUE TITLE
When used with sd-dynamic-thresholding custom node produces noisy images.

### ISSUE THREAD

**Issue by toyxyz** [shiimizu/ComfyUI_smZNodes#26]
When used with sd-dynamic-thresholding custom node, it produces noisy images.

sd-dynamic-thresholding: https://github.com/mcmonkeyprojects/sd-dynamic-thresholding
ComfyUI workflow : [test.json](https://github.com/shiimizu/ComfyUI_smZNodes/files/13197981/test.json)

![image](https://github.com/shiimizu/ComfyUI_smZNodes/assets/8006000/43aaf674-f168-4141-88a5-2f81c9ab2c03)
![image](https://github.com/shiimizu/ComfyUI_smZNodes/assets/8006000/2972d3d2-39fb-4178-858f-1840bc410ecc)

**Comment by shiimizu** [comment]
I think it's an issue with https://github.com/mcmonkeyprojects/sd-dynamic-thresholding because I get the same noisiness on the default CLIP Text Encode node.
