### ISSUE TITLE
[CRITICAL BUG] Nodes can't be found anymore

### ISSUE THREAD

**Issue by isben** [shiimizu/ComfyUI_smZNodes#27]
I noticed today (but it could be be the case since a few days) that none of the smzNodes appear in the ComfyUI nodes list when I try to add one. I update my ComfyUI almost daily and I noticed smzNodes were updated on several occasions recently.
Also, when loading an image generated with the smzNodes, I get an error message saying the nodes were not found and they are displayed in red on the workflow. Though, the Comfy-Manager shows them installed and enabled.

**Comment by DrJKL** [comment]
I think this is probably related to https://github.com/jags111/efficiency-nodes-comfyui/issues/10

**Comment by DrJKL** [comment]
Yup, the changes in https://github.com/jags111/efficiency-nodes-comfyui/pull/12 and removing DDIM from `__init__.py` got the nodes to load properly.

**Comment by DrJKL** [comment]
It does fail at sampling time. Probably needs some more work to adjust to the recent comfyui sampling code changes.

**Comment by isben** [comment]
Thanks for the news. I, indeed, updated my Efficiency nodes to version 2 a couple days ago.

**Comment by jags111** [comment]
I am checking for this and will add a possible feedback for same.. Thanks for pointing this out and will check if I am able to push the modifications through.

**Comment by shiimizu** [comment]
Should be fixed in https://github.com/shiimizu/ComfyUI_smZNodes/commit/c4988de4e812a9475c14349ff63c00d9253c02da

**Comment by isben** [comment]
I confirm my issues have been solved with the latest changes.
Thanks to all for the prompt reaction.
