### ISSUE TITLE
tuple index out of range

### ISSUE THREAD

**Issue by Lokrer** [shiimizu/ComfyUI_smZNodes#29]
First, thanks for providing a node which promises to do exactly what I was looking for!!

I get the following error: 

Error occurred when executing smZ CLIPTextEncode:

tuple index out of range

File "/Users/lucasadrian/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...

It then continues on like that. 

Running Comfy on a M1 Mac. 

Any ideas on how I can fix this?

**Comment by shiimizu** [comment]
Can you post the full stack trace and provide a workflow? Also, make sure you've updated ComfyUI.

**Comment by Lokrer** [comment]
A bit embarrassing, but updating ComfyUI solved it. Sorry that I hadn't though of that before posting, I just got startet with Comfy. Thanks for your quick help!
