### ISSUE TITLE
BUG/USAGE: "BREAK" Keyword in "CLIP Text Encode++" always create female characters

### ISSUE THREAD

**Issue by BaronFalke** [shiimizu/ComfyUI_smZNodes#31]
I am playing around with the A111 parser style of the CLIP Text Encode++.
For female characters it works perfectly:
![image](https://github.com/shiimizu/ComfyUI_smZNodes/assets/6080245/3b1bfc1d-2324-403f-8d33-7e565d36da21)

But after changing "woman" to "man", it still delivers female characters:
![image](https://github.com/shiimizu/ComfyUI_smZNodes/assets/6080245/d5b7eae6-eea8-4dcd-97cc-df870e7bf0a1)

I firt thought that maybe the chunk with "man" is getting lost since the other chunks describe typical "female" stuff like "skirt".
So I changed the prompt to only include hair:
![image](https://github.com/shiimizu/ComfyUI_smZNodes/assets/6080245/31ae1e8b-8dd0-4684-bcb1-c2accf2374c7)

The result for "man":
![image](https://github.com/shiimizu/ComfyUI_smZNodes/assets/6080245/c183b151-7473-4a47-b79e-950871985a00)

If I remove the "BREAK" keyword, then the result is as expected:
![image](https://github.com/shiimizu/ComfyUI_smZNodes/assets/6080245/89b6ba23-b96f-4794-a0b1-73caaf58f4ea)

So briefly: the keyword "BREAK" seems to always generate female characters.
Is this supposed to be this way? Or am I using it wrong way? Or are there other settings which I fu*ked up?
Or is it possible, that "man" is also a keyword in your custom node?

**Comment by shiimizu** [comment]
The code I used is taken from [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) and it appears the same behaviour occurs there as well. If it happens on your system as well, it would be best to report it upstream also.

**Comment by BaronFalke** [comment]
Okay, I was just surprised since this is really all the time.
I also figured out that in other cases it helps to write "male man" or "female woman" ... maybe "man" and "woman" are not supported by some models.

I will try it out with other keywords. Else  I only can colorize woman ... ^^
Maybe it's an issue for huggingface?
