### ISSUE TITLE
Prompts not saved into PNG info

### ISSUE THREAD

**Issue by Cahya** [shiimizu/ComfyUI_smZNodes#40]
Hi,

When I use Clip Text Encode++, prompts are not saved into PNG files.

**Comment by shiimizu** [comment]
My nodes have nothing to do with metadata. Perhaps it's the work of another custom node?

**Comment by shiimizu** [comment]
My nodes have nothing to do with the metadata/PNG info. Perhaps it's the work of another custom node?
