### ISSUE TITLE
Weight numbers not applied to embeddings

### ISSUE THREAD

**Issue by MalikKillian** [shiimizu/ComfyUI_smZNodes#41]
Pretty sure I've experimented enough to see a gap in the processing. A negative prompt like this, `(easynegative:6)`, should understandably make an ugly image because of over emphasis on the embedding. However, with smZ CLIPTextEncode I see no difference between `(easynegative)` and `(easynegative:6)` or `(easynegative:6.0)` or `(embedding:easynegative:6.0)`. I can only get the weight of an embedding to change if I do something like `((((easynegative))))`. It seems like the behavior is the same weather used in positive or negative conditioning.

**Comment by shiimizu** [comment]
Thanks for discovering that! It should be fixed in https://github.com/shiimizu/ComfyUI_smZNodes/commit/e0ddb5d495a3bb59ccc2a373422c24192a532d4a
