### ISSUE TITLE
ERROR:root:!!! Exception during processing !!! since last update (~1 Hr ago)

### ISSUE THREAD

**Issue by Nem-z** [shiimizu/ComfyUI_smZNodes#42]
Greetings,

I'm encountering an error with this node since I updated comfy. I used the manager to fetch update and update all at once like I always do. But this time I have this message whenever I try to queue a work with your node (works as intended with the Comfy default one).

I also tried to delete the `smZNodes` folder and do a `git clone` again but the issue persist.

> ERROR:root:!!! Exception during processing !!!
> ERROR:root:Traceback (most recent call last):
>   File "G:\WebUI\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\WebUI\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\WebUI\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\WebUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\nodes.py", line 87, in encode
>     result = run(**params)
>              ^^^^^^^^^^^^^
>   File "G:\WebUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 713, in run
>     conds_list, cond = reconstruct_schedules(schedules, x)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\WebUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 401, in reconstruct_schedules
>     cond = fn(schedules, step)
>            ^^^^^^^^^^^^^^^^^^^
>   File "G:\WebUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\prompt_parser.py", line 295, in reconstruct_cond_batch
>     param = c[0][0].cond
>             ~^^^
> KeyError: 0

Let me know if I can do anything else to help troubleshoot this issue.

Cheers!

**Comment by shiimizu** [comment]
Do you have a workflow that I can test?

**Comment by shiimizu** [comment]
Possibly related to https://github.com/shiimizu/ComfyUI_smZNodes/issues/44

**Comment by Kicher2006** [comment]
How do you solve the problem?
