### ISSUE TITLE
Validation running examples settings workflow

### ISSUE THREAD

**Issue by DoctorDevMan** [shiimizu/ComfyUI_smZNodes#43]
Error when trying to run your example settings workflow:

https://private-user-images.githubusercontent.com/54494639/270232176-31427491-f313-4fa4-be7e-18333cba4de6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1OTg0NjEsIm5iZiI6MTcwMzU5ODE2MSwicGF0aCI6Ii81NDQ5NDYzOS8yNzAyMzIxNzYtMzE0Mjc0OTEtZjMxMy00ZmE0LWJlN2UtMTgzMzNjYmE0ZGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDEzNDI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZDY2ZWQyOGEyMWYxNzg5ZTg5OWE4MDI3ZjdjNzcxODRiMDIzMTg0MWRlNDZmNjhiNTEyMmE5MTEzMjY3MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_yRIXClmclWkpHaWWSou4OjPJh8oiVnwUVX6_Wd6fs

![image](https://github.com/shiimizu/ComfyUI_smZNodes/assets/22381913/a81f09b1-bdbd-4e82-9d69-f813c8290447)

**Comment by shiimizu** [comment]
The example workflow was out of date.  Please recreate the node.
