### ISSUE TITLE
Settings (smZ) node does not display all settings

### ISSUE THREAD

**Issue by Cahya** [shiimizu/ComfyUI_smZNodes#49]
Hello,
I updated ComfyUI and smZNodes. Then I started fresh and used the workflow from Load Default. I added the Settings (smZ) node, but strangely not all settings were displayed.
<img width="779" alt="smz" src="https://github.com/shiimizu/ComfyUI_smZNodes/assets/648408/f344eb0c-a88e-43df-a4b2-60654e807f42">

**Comment by shiimizu** [comment]
It depends on the input you give it. Give it a `MODEL` input and watch it change.

**Comment by Cahya** [comment]
Oh I see. Thanks!
