### ISSUE TITLE
prompt switching broken in the latest update

### ISSUE THREAD

**Issue by MotorMan** [shiimizu/ComfyUI_smZNodes#5]
it looks like the prompt switching was broken with the IT/s degradation fix from 4 days ago.  
i was able to verify that the alternating prompt switching, [subject1|subject2|subject3] is no longer alternating, and instead appears to be as if the [|] characters were stripped (i haven't tested to see if that is the actual case or not)
you can tell by the preview in the sampler no longer flashing between the subjects like before. now it's a solid-smooth gen.

attached is an example from a previous version i recorded to show what a good prompt switching looks like.
![ezgif com-video-to-gif (1)](https://github.com/shiimizu/ComfyUI_smZNodes/assets/899728/74fa7f50-0442-4938-b21a-f4db3a3217d2)

hopefully this info will help, and if you have any questions, just let me know.

**Comment by shiimizu** [comment]
I can't seem to reproduce this. Can you post a workflow?

**Comment by MotorMan** [comment]
![ComfyUI_00034_](https://github.com/shiimizu/ComfyUI_smZNodes/assets/899728/9e0e1604-5e8e-4416-8e46-6e44478030c1)
here is the original workflow i used to make the gif above.  the picture is also the actual final image, since right now i have the old node version in for testing. i'll post a pic of the new version in a few minutes. let me know if github strips the metadata from the png or not. you should be able to just drag/drop it to your comfyui to get the workflow.

**Comment by MotorMan** [comment]
ok i came up with a pretty good way to show the issue. prompt is "RAW Photograph, a [potato|soccer ball], outdoors,"
in the new version, all you get is a plain potato. and in the old version, it's clearly a nice mix between a soccer ball and a potato. here are example images(same seeds):
![ComfyUI_00039_](https://github.com/shiimizu/ComfyUI_smZNodes/assets/899728/7e20eb73-c826-4fc7-b990-d11336efbf9c)
![ComfyUI_00040_](https://github.com/shiimizu/ComfyUI_smZNodes/assets/899728/b361853d-fed2-4868-b240-5dcf42442f05)
really hope this helps! =)

**Comment by shiimizu** [comment]
Are you sure you're on the latest commit? Can you try re-installing the node?

**Comment by MotorMan** [comment]
now that is interesting. i know i was up-to-date on it before(i even checked manager to make sure), since the IT/s degradation was gone, and i had updated it via the manager.
i went and deleted the folder, ran comfyui to verify it had the node missing, also noticed smZNodes was not available as a "install missing nodes" for some reason, but then closed it, and ran cmd, and git clone'd the repo to the custom nodes dir, and started comfyui again, and ran the test, and it's clearly prompt switching again.  after pondering this a few min i think i might of gotten stuck on an in-between version. smZNodes is no longer showing up in manager as an available node or an installable one, so that may have gotten me stuck on  the 8-21-23 11:18pm version. i'll have to check my other comfyui installs to make sure, but as of now, i think i'll call this good and the problem was comfyUI manager not updating the node. thanks again for your help!
