### ISSUE TITLE
Alternate words invalid,text replace is not supported, which is strange.

### ISSUE THREAD

**Issue by MagicShiba** [shiimizu/ComfyUI_smZNodes#50]
As shown in the picture, after various text replacement tests, the alternate words will become invalid, which is strange.
Everything works fine without text replacement.
It is normal for the replaced text to be used directly.
(machine translation)
![workflow](https://github.com/shiimizu/ComfyUI_smZNodes/assets/118909774/05432a0c-6f27-4391-8120-280585ed6ae6)

**Comment by shiimizu** [comment]
Related to https://github.com/shiimizu/ComfyUI_smZNodes/issues/51
