### ISSUE TITLE
no settings !!! please help

### ISSUE THREAD

**Issue by max140x** [shiimizu/ComfyUI_smZNodes#53]
![Screenshot 2024-01-25 180154](https://github.com/shiimizu/ComfyUI_smZNodes/assets/153641803/92a3b1e9-8f6a-42ab-87e6-b9a777956950)

**Comment by shiimizu** [comment]
Connect a $\color{magenta}{MODEL}$ or $\color{yellow}{CLIP}$ input as shown [here](https://github.com/shiimizu/ComfyUI_smZNodes#settings).

**Comment by max140x** [comment]
> Connect a MODEL or CLIP input as shown [here](https://github.com/shiimizu/ComfyUI_smZNodes#settings).

thank you sooooooooooo much

**Comment by max140x** [comment]
solve it
