### ISSUE TITLE
[Feedback] Sample workflow file + Lora Stacker

### ISSUE THREAD

**Issue by strouder** [shiimizu/ComfyUI_smZNodes#54]
Hello... how do we add a lora stack in this? I'm new to comfy UI ... do yuo have a sample workflow file to make this work?

**Comment by shiimizu** [comment]
That depends on which LoRA stacker. I assume you're referring to the one from Efficiency Nodes? If so, here's a [workflow.json](https://github.com/shiimizu/ComfyUI_smZNodes/files/14259495/workflow_.json)
