### ISSUE TITLE
How to generate same image as a1111 webui?

### ISSUE THREAD

**Issue by wodsoe** [shiimizu/ComfyUI_smZNodes#60]
How to generate same image as a1111 webui?
Is there any example workflow?

**Comment by alenknight** [comment]
it's VERY hard. you can't get it 100% but i've found if you leverage smzSettings along with Auto1111 cliptextencode nodes... you can get 90% identical.  also depends the model.
with Pony Diffusion i'm developing a workflow that returns 99% identical to Auto1111... however in other models it's around 85%.

note. this doesn't mean quality.  I mean just same image.  same seed. same image. same pose and composure.

quality is based on other stuff and out the box comfyui produces equal quality to Automatic1111
