### ISSUE TITLE
(IMPORT FAILED):  ComfyUI\custom_nodes\ComfyUI_smZNodes

### ISSUE THREAD

**Issue by Piscabo** [shiimizu/ComfyUI_smZNodes#62]
ComfyUI Revision: 2111 [38ed2da2] | Released on '2024-04-05'

Cannot import H:\ComfyUI\custom_nodes\ComfyUI_smZNodes module for custom nodes: module 'comfy.samplers' has no attribute 'CFGNoisePredictor'

**Comment by criyle** [comment]
This sampler was remove in this commit: https://github.com/comfyanonymous/ComfyUI/commit/0542088ef895b4825df80fd3babf91513441af65

**Comment by criyle** [comment]
Older version of ComfyUI works, you may try `git reset --hard 6c6a39251fe313c56a88c90d820009073b623dfe`

**Comment by Zakutu** [comment]
me too

**Comment by Zakutu** [comment]
> ComfyUI の古いバージョンは動作します。試してみてください`git reset --hard 6c6a39251fe313c56a88c90d820009073b623dfe`

In which directory should I run that command?

**Comment by criyle** [comment]
> > ComfyUI の古いバージョンは動作します。試してみてください`git reset --hard 6c6a39251fe313c56a88c90d820009073b623dfe`
> 
> In which directory should I run that command?

In `ComfyUI` directory, outside of the `custom_nodes`

**Comment by Zakutu** [comment]
> > > ComfyUI の古いバージョンは動作します。試してください。`git reset --hard 6c6a39251fe313c56a88c90d820009073b623dfe`
> > 
> > 
> > どのディレクトリでそのコマンドを実行すればよいでしょうか?
> 
> ディレクトリ内`ComfyUI`、外部`custom_nodes`

thank you so much

**Comment by Piscabo** [comment]
So will the node be updated? I see no point in going backward...

**Comment by shiimizu** [comment]
Chilll~ it was just a couple of days of new changes haha

**Comment by Piscabo** [comment]
> Chilll~ it was just a couple of days of new changes haha
I was just asking... don tell me to 'chill'
Can't do much if my workflow looks like this. Be glad someone is using your nodes... 
![image](https://github.com/shiimizu/ComfyUI_smZNodes/assets/123719842/84bc91c4-21c1-4fac-9eee-a7fb6c4fa159)

**Comment by alenknight** [comment]
> > Chilll~ it was just a couple of days of new changes haha
> > I was just asking... don tell me to 'chill'
> > Can't do much if my workflow looks like this. Be glad someone is using your nodes...
> > ![image](https://private-user-images.githubusercontent.com/123719842/320208945-84bc91c4-21c1-4fac-9eee-a7fb6c4fa159.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzI4NDEsIm5iZiI6MTcxMjQ3MjU0MSwicGF0aCI6Ii8xMjM3MTk4NDIvMzIwMjA4OTQ1LTg0YmM5MWM0LTIxYzEtNGZhYy05ZWVlLWE3ZmI2YzRmYTE1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwNjQ5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWMyNzUwY2IwZjExOGQzNjIyYjQwMzk5ODdiZjI1NzMzNWJlM2M5MjFlN2RhY2VlNDFjNDhhN2NiOWQzMWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f5LqvUlIQeJ4I2hBSke8B-3aNyW7-hCqwzvpwg1P7mI)

you do realize we don't pay for this?  i DO want an update sure... but i'd be cautious about complaining.  be glad someone patches and offers help.  

all that being said... sure will be nice when there's a patch eventually :)

**Comment by Piscabo** [comment]
Oh, gee whiz... I was asking a stupid question and also alerting to a problem. Keep your pants on.
You all do amazing work (and for an open-source community). But you can't go around telling people to 'chill', if they were asking a general question. If you feel you have to stop maintaining then that is your prerogative.


> > > Chilll~ it was just a couple of days of new changes haha
> > > I was just asking... don tell me to 'chill'
> > > Can't do much if my workflow looks like this. Be glad someone is using your nodes...
> > > ![image](https://private-user-images.githubusercontent.com/123719842/320208945-84bc91c4-21c1-4fac-9eee-a7fb6c4fa159.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzI4NDEsIm5iZiI6MTcxMjQ3MjU0MSwicGF0aCI6Ii8xMjM3MTk4NDIvMzIwMjA4OTQ1LTg0YmM5MWM0LTIxYzEtNGZhYy05ZWVlLWE3ZmI2YzRmYTE1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwNjQ5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWMyNzUwY2IwZjExOGQzNjIyYjQwMzk5ODdiZjI1NzMzNWJlM2M5MjFlN2RhY2VlNDFjNDhhN2NiOWQzMWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f5LqvUlIQeJ4I2hBSke8B-3aNyW7-hCqwzvpwg1P7mI)
> 
> you do realize we don't pay for this? i DO want an update sure... but i'd be cautious about complaining. be glad someone patches and offers help.
> 
> all that being said... sure will be nice when there's a patch eventually :)
