### ISSUE TITLE
One of the more recent updates have broken smZNodes  and it fails to load

### ISSUE THREAD

**Issue by axdwct** [shiimizu/ComfyUI_smZNodes#63]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 55, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\nodes.py", line 7, in <module>
    from .modules.sd_hijack import model_hijack
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\sd_hijack.py", line 12, in <module>
    from ..smZNodes import FrozenCLIPEmbedderWithCustomWordsCustom, FrozenOpenCLIPEmbedder2WithCustomWordsCustom, get_learned_conditioning
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 954, in <module>
    CFGNoisePredictorOrig = comfy.samplers.CFGNoisePredictor
AttributeError: module 'comfy.samplers' has no attribute 'CFGNoisePredictor'

**Comment by DreamLoveBetty** [comment]
It seems that the updated smznodes.py defines a CFGNoisePreditorOrig class method to be imported into a class from comfy/samplers. py, but there is no implementation for this class in comfy/samplers. py. Request an update to resolve the issue.

**Comment by fernicar** [comment]
For now you can delete this line from "custom_nodes\ComfyUI_smZNodes\smZNodes.py":
https://github.com/shiimizu/ComfyUI_smZNodes/blob/52fb739a640366eb3ef18be4ecccd87c3a5fd8e8/smZNodes.py#L954

and you can replace the next line:
https://github.com/shiimizu/ComfyUI_smZNodes/blob/52fb739a640366eb3ef18be4ecccd87c3a5fd8e8/smZNodes.py#L955
to this line:
class CFGNoisePredictor():

to workaround until the next update.

**Comment by alenknight** [comment]
> For now you can delete this line from "custom_nodes\ComfyUI_smZNodes\smZNodes.py":
> 
> https://github.com/shiimizu/ComfyUI_smZNodes/blob/52fb739a640366eb3ef18be4ecccd87c3a5fd8e8/smZNodes.py#L954
> 
> and you can replace the next line:
> 
> https://github.com/shiimizu/ComfyUI_smZNodes/blob/52fb739a640366eb3ef18be4ecccd87c3a5fd8e8/smZNodes.py#L955
> 
> 
> to this line:
> `class CFGNoisePredictor():`
> to workaround until the next update.

thank you!  this worked for now!  appreciate it

**Comment by SquidPuffer** [comment]
> For now you can delete this line from "custom_nodes\ComfyUI_smZNodes\smZNodes.py":
> 
> https://github.com/shiimizu/ComfyUI_smZNodes/blob/52fb739a640366eb3ef18be4ecccd87c3a5fd8e8/smZNodes.py#L954
> 
> and you can replace the next line:
> 
> https://github.com/shiimizu/ComfyUI_smZNodes/blob/52fb739a640366eb3ef18be4ecccd87c3a5fd8e8/smZNodes.py#L955
> 
> 
> to this line:
> `class CFGNoisePredictor():`
> to workaround until the next update.

Thanks, worked.

**Comment by HydraBucket** [comment]
I couldnt get this working... Can I have a link to a git to clone to replace my node?
