### ISSUE TITLE
AttributeError: module 'comfy.samplers' has no attribute 'CFGNoisePredictor'

### ISSUE THREAD

**Issue by emourdavid** [shiimizu/ComfyUI_smZNodes#64]
Hi,

I have issue when run your Node. All my nodes upgraded to latest version. When it run, it shows like following:

From console: ComfyUI_smZNodes/smZNodes.py", line 954, in <module>
CFGNoisePredictorOrig = comfy.samplers.CFGNoisePredictor
AttributeError: module 'comfy.samplers' has no attribute 'CFGNoisePredictor'

Can you specific which version / environment you installed? Thanks

**Comment by wsry888** [comment]
same issue

**Comment by emourdavid** [comment]
The version commit **6c6a392** of ComfyUI can run properly. The latest version will break down smzNodes

Run > git reset --hard 6c6a392  inside ComfyUI folder
