### ISSUE TITLE
Settings node show up stranglely

### ISSUE THREAD

**Issue by Gerkinfeltser** [shiimizu/ComfyUI_smZNodes#67]
Settings node show up very strangely. Not at all like what is shown in the Readme.md. Most settings not visible:
EDIT: (Apparently the fields are hidden behind the "placeholder" texts & un-editable because of this)
![image](https://github.com/shiimizu/ComfyUI_smZNodes/assets/1477787/f0aed068-08d5-4417-968c-6bb690d3f991)

**Comment by shiimizu** [comment]
It might be because you have [ComfyUI-0246](https://github.com/Trung0246/ComfyUI-0246)’s alternative DOM widget setting enabled.

**Comment by Gerkinfeltser** [comment]
You are correct! Disabling that fixed it up. Thank you!
