### ISSUE TITLE
Longer prompts Getting truncated at 77 tokens

### ISSUE THREAD

**Issue by Avalov-S** [shiimizu/ComfyUI_smZNodes#72]
Hi,

First off, its is a very good node, allowing to reproduce exact results as in WebUI, (other nodes which claim to do similar thing don't get this close)

However, there is an error/warning that happens with longer prompts as below when using the smzClipTextEncode Node

```
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
Requested to load SDXLClipModel
Loading 1 new model
Token indices sequence length is longer than the specified maximum sequence length for this model (85 > 77). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (85 > 77). Running this sequence through the model will result in indexing errors
leftover keys: dict_keys(['down_blocks.1.attentions.0.norm.bias', 'down_blocks.1.attentions.0.norm.weight', 'down_blocks.1.attentions.0.proj_in.bias', 'down_blocks.1.attentions.0.proj_in.weight', 'down_blocks.1.attentions.0.proj_out.bias', 'down_blocks.1.attentions.0.proj_out.weight', 'down_blocks.1.attentions.1.norm.bias', 'down_blocks.1.attentions.1.norm.weight', 'down_blocks.1.attentions.1.proj_in.bias', 'down_blocks.1.attentions.1.proj_in.weight', 'down_blocks.1.attentions.1.proj_out.bias', 'down_blocks.1.attentions.1.proj_out.weight'])
Requested to load AutoencoderKL
Loading 1 new model
Requested to load SDXL
Requested to load ControlNet
Loading 2 new models
```

Other details:

1) This happens only when using the smzCliptextencode node with long prompts
2) The issue doesn't happen when using default clip encoders that come with comfyui or other nodes for the same long prompts, as they seem to split the prompt into batches of 77 tokens 
3) Using Conditioning combine/average/concat nodes doesn't produce the same results as the single long prompt ( splitting the prompt into 2 smaller parts and using concat makes the warning stop, but the results are different vs. what should appear if the prompt were conditioned as a single , long text)
4) The workflow proceeds to execute, but with only the first 77 tokens of the prompt , when using the smzcliptextencode, while rest are getting truncated i guess

Request if you can check into this issue and add a feature like default cliptextencode to automatically split longer prompt into batches of 77 tokens,

Let me know if any further details are required.

**Comment by shiimizu** [comment]
Thanks for the report. I noticed this myself, somewhere along the myriad of ComfyUI updates, the warning started to appear. I don't know why WebUI doesn't have it. Forge explicitly [suppresses it](https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/4e3c78178a7eae73311fb269cdeaf7a0b40644d1/backend/loader.py#L46), so I suspect A1111 does so as well somewhere. In ComfyUI, the tokenizer never deals with text exceeding 77 tokens since it tokenizes every word rather than every long piece of text. For now, I've opted to do the same as Forge. It's fine since it doesn't actually truncate tokens.
