### ISSUE TITLE
`multi_conditioning` broke

### ISSUE THREAD

**Issue by shiimizu** [shiimizu/ComfyUI_smZNodes#83]
The `AND` feature hasn't been maintained for a while now due to lots of upstream changes in ComfyUI. Tbh, this technology has been superseded by recent research and works, so I'm not sure if it's worth maintaining or including anymore. A1111 should deprecate it. I only have it here for reproducibility reasons.

**Comment by sadsilly** [comment]
Please maintain it ! i love this add on its only reason i use comfy over auto. because i can have auto prompting in comfy. 

<3

**Comment by drozbay** [comment]
I'm curious, what are the other technologies that have superseded the functionality of multi-conditioning? I would be interested in trying to help fix this AND feature but if there is something else that accomplishes the same thing that would be fine too.

**Comment by shiimizu** [comment]
You can check out the myriad of [papers](https://scholar.google.com/scholar?hl=en&as_sdt=2005&sciodt=0,5&cites=12245459038718110522&scipsc=&q=&scisbd=1) that cite the original Composable-Diffusion paper.

**Comment by shiimizu** [comment]
@sadsilly
Thanks. I'm glad to hear you like it. I'll get around to it and have it fixed. I've just been busy with my studies.

@drozbay
You can check out the myriad of [papers](https://scholar.google.com/scholar?hl=en&as_sdt=2005&sciodt=0,5&cites=12245459038718110522&scipsc=&q=&scisbd=1) that cite the original Composable-Diffusion paper.

**Comment by sadsilly** [comment]
i look forward to the fix <3 <3 <3 :D
