### ISSUE TITLE
Compatibility with AITemplate

### ISSUE THREAD

**Issue by masslevel** [shiimizu/ComfyUI_smZNodes#9]
Hi @shiimizu.

Thank you for making this! Prompt editing is one of the features I really missed from a1111.

Would it be possible to add compatibility for [AITemplate](https://github.com/FizzleDorf/AIT)? AITemplate can improve the speed of generating images on Nvidia 3000 and 4000 series cards from 50 - 100 %.

If you bypass or remove the AITemplate Loader node in a workflow, smZNodes is working fine. Otherwise the following error message appears:
`AttributeError: 'AITemplateModelWrapper' object has no attribute 'num_timesteps'`

Of course this might totally be something that needs to be updated in the AIT node and not sMZNodes. But I thought I ask here too, since you're already hijacking and hooking into a couple of functions.

Someone opened an [issue](https://github.com/FizzleDorf/AIT/issues/52) about this on the AIT repo and I added some context.

**Comment by shiimizu** [comment]
Thanks for bring this to my attention. It should be fixed in https://github.com/shiimizu/ComfyUI_smZNodes/commit/f3d170f1974fc10f2d9dc9118f02c04fa8608f46.

**Comment by shiimizu** [comment]
Thanks for bringing this to my attention. It should be fixed in https://github.com/shiimizu/ComfyUI_smZNodes/commit/f3d170f1974fc10f2d9dc9118f02c04fa8608f46.

**Comment by masslevel** [comment]
Works perfectly! Fantastic. I will continue doing more advanced syntax tests and thank you for the fast fix!
