### ISSUE TITLE
Blend from compel

### ISSUE THREAD

**Issue by andupotorac** [shiimizu/ComfyUI_smZNodes#94]
When trying to use **("spider man", "robot mech").blend(1, 0.8)** from Compel, I get this error. It works when I don't use this prompt format.

<img width="1300" alt="Screenshot 2024-08-12 at 18 58 05" src="https://github.com/user-attachments/assets/f338a903-0526-4b2a-bace-315aad49f581">

**Comment by shiimizu** [comment]
Thanks for the heads up. I took the compel implementation from [SD.Next](https://github.com/vladmandic/automatic), so that means they also don't have `blend`.

**Comment by andupotorac** [comment]
Got it, it would be useful! Thanks.
