### ISSUE TITLE
[smZNodes]: 'utf-8' codec can't decode byte 0xd3 in position 8129: invalid continuation byte

### ISSUE THREAD

**Issue by alenhrp** [shiimizu/ComfyUI_smZNodes#95]
I don't know what it is and how to fix it

**Comment by shiimizu** [comment]
Do you have a workflow I can test? I suspect it has something to do with your prompt.

**Comment by shiimizu** [comment]
That means an error occurred when trying to read your `web/scripts/widgets.js` file.
