### ISSUE TITLE
"smZ Settings" caused comfyui rendering to crash

### ISSUE THREAD

**Issue by MagicShiba** [shiimizu/ComfyUI_smZNodes#96]
As shown in the figure, many nodes do not display and are stuck.
![cfxr](https://github.com/user-attachments/assets/f4e61760-0333-4b2c-89cc-756ba4e59024)
![smzxrbk](https://github.com/user-attachments/assets/57c29acb-ded5-4ca0-810f-e0d5360ab2b4)

By removing the other nodes, you can prove that the smZ Settings are causing the problem.
![屏幕截图 2024-08-19 035650](https://github.com/user-attachments/assets/0163f025-d853-45a8-a28b-502a0c582931)
![屏幕截图 2024-08-19 035709](https://github.com/user-attachments/assets/9578887e-789c-437f-9d60-85b28d425399)
(Machine translation)

**Comment by shiimizu** [comment]
It should be fixed now.
